### ISSUE TITLE
scale factor in prototype distance loss?

### ISSUE THREAD

**Issue by Zakiyi** [VSainteuf/metric-guided-prototypes-pytorch#1]

**Comment by Zakiyi** [comment]
Hi there,
Thank you for sharing your code. It is quite interesting. And have read your paper and code,  I wonder the scale factor in prototype distance loss is updated during training? but I did not find the scale factor in the DistortionLoss().

best,
zhen

**Comment by VSainteuf** [comment]
Hi,
Thanks for your interest, and also for pointing this problem out.
Turns out the code in this repo is a bit outdated. 
I just pushed the updated version. In this version the `DistortionLoss` is scale-free by default and you can get the fixed-scale distortion loss with `DistortionLoss(D=D, scale_free=False)`.
Hope this helps!
